baseURL = 'https://nothr.in/'
languageCode = 'en-us'
title = 'Harshith Reddy / nothr'
disableKinds = ["taxonomy"]
enableGitInfo = true

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"
[markup]
[markup.goldmark]
[markup.goldmark.extensions]
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
[params]
math = true
